version: '3.3'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
        - './data:/usr/share/nginx/html'
    ports:
        - '8001:80'

  gin_fileserver:
    image: accalina/gin_fileserver:1.0
    container_name: gin_fileserver
    volumes:
      - './data:/api/public/'
    ports:
      - "8002:8090"